name: Problem or Mistake Report
description: File a mistake or problem report
title: "[Problem]: "
labels: [ "problem" ]
body:
- type: textarea
  id: whats-wrong
  attributes:
    label: What's wrong?
    description: Also tell us how you think it should be written or what content is missing?
    placeholder: Tell us what you see!
    value: "A problem or mistake happened!"
  validations:
    required: true
- type: dropdown
  id: module
  attributes:
    label: Module
    description: What course module has this problem or mistake?
    options:
    - Structure
    - Content
    - Module 01
    - Module 02
    - Module 03
    - Module 04
    - Module 05
    - Module 06
    - Module 07
    - Module 08
    - Module 09
    - Module 10
    - Final Challenge
    default: 0
  validations:
    required: true
